version: "3.7"
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: polar
      MONGO_INITDB_ROOT_PASSWORD: polar-password
      MONGO_INITDB_DATABASE: polar_db
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

  flutter-app:
    image: ghcr.io/cirruslabs/flutter:3.13.0
    ports:
      - 8080:8080

  mongo-api:
    image: node:latest
    ports:
      - 3000:3000

networks:
  sail:
    driver: bridge
volumes:
  mongodb:
    driver: local
