version: '3.7'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_USER}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASSWORD}'
      MONGO_INITDB_DATABASE: '${MONGO_DB_NAME}'
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  postgres:
    image: postgres:14-alpine
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - path: ./.env
        required: true
    environment:
      POSTGRES_PASSWORD: '${DB_PASS}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_DB: '${DB_NAME}'
networks:
  sail:
    driver: bridge
volumes:
  mongodb:
    driver: local
  postgres:
    driver: local
