version: "3.7"
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: polar
      MONGO_INITDB_ROOT_PASSWORD: polar-password
      MONGO_INITDB_DATABASE: polar_db
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

networks:
  sail:
    driver: bridge

volumes:
  mongodb:
    driver: local
