name: hatofit
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.4.0

  # BLE
  polar: ^6.0.0
  flutter_blue_plus: ^1.5.2

  # State Management
  get: ^4.6.5

  # Preferences
  shared_preferences: ^2.2.0

  # Generator
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1
  build_runner: ^2.4.5
  image: ^4.0.17
  # UI
  flutter_svg: ^2.0.7
  lottie: ^2.4.0
  fl_chart: ^0.63.0
  syncfusion_flutter_charts: ^22.2.9
  youtube_player_flutter: ^8.1.2
  cached_network_image: ^3.2.3
  horizontal_picker: ^1.2.0
  circular_countdown_timer:
    git:
      url: https://github.com/ceranco/circular_countdown_timer
      ref: on_change_fix
  image_picker: ^1.0.1
  video_player: ^2.7.0

  # Utils
  intl: ^0.18.1
  path_provider: ^2.0.15
  permission_handler: ^10.4.1
  # flutter_dotenv: ^5.1.0
  # background_fetch: ^1.2.0
  dartz: ^0.10.1
  logger: ^2.0.1

  # Notifications
  flutter_local_notifications: ^15.1.0+1

  # Analytics
  # sentry_flutter: ^7.8.0
  firebase_performance: ^0.9.2+4
  firebase_core: ^2.15.0
  firebase_analytics: ^10.4.4
  mocktail: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/image.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    # - .env
    - assets/
    - assets/images/
    - assets/images/logo/
    - assets/images/polar/
    - assets/animations/
    - assets/videos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
