name: hatofit
version: 1.0.0+1
publish_to: none
description: A new Flutter project.

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.4.0

  # BLE
  polar: ^6.0.1
  flutter_blue_plus: ^1.5.2

  # State Management
  get: ^4.6.5

  # Preferences
  shared_preferences: ^2.2.0

  # Generator
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1
  build_runner: ^2.4.5
  image: ^4.0.17

  # UI
  flutter_svg: ^2.0.7
  flutter_neumorphic_plus: ^3.3.0
  lottie: ^2.4.0
  fl_chart: ^0.63.0
  syncfusion_flutter_charts: ^21.2.6
  youtube_player_flutter: ^8.1.2
  cached_network_image: ^3.2.3
  horizontal_picker: ^1.2.0
  circular_countdown_timer:
    git:
      url: https://github.com/ceranco/circular_countdown_timer
      ref: on_change_fix
  image_picker: ^1.0.1
  video_player: ^2.7.0

  # Utils
  intl: ^0.18.1
  path_provider: ^2.0.15
  permission_handler: ^10.4.1
  flutter_dotenv: ^5.1.0
  # background_fetch: ^1.2.0

  # Notifications
  flutter_local_notifications: ^15.1.0+1
  flutter_native_splash: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/hatofit.png"
  min_sdk_android: 28

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/
    - assets/images/logo/
    - assets/images/polar/
    # - assets/animations/
    - assets/videos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
