name: hatofit
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"
  
dependencies:
  circular_countdown_timer:
    git:
      url: https://github.com/ceranco/circular_countdown_timer
      ref: on_change_fix
  cached_network_image: ^3.3.0
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.5
  firebase_analytics: ^10.7.0
  firebase_core: ^2.22.0
  firebase_crashlytics: ^3.4.4
  firebase_performance: ^0.9.3+4
  flutter:
    sdk: flutter

  # Localization
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
    
  flutter_reactive_ble: ^5.2.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^12.1.1
  health: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  oktoast: ^3.4.0
  syncfusion_flutter_charts: ^23.1.44
  flutter_local_notifications: ^16.1.0
  syncfusion_flutter_gauges: ^23.1.44
  image_picker: ^1.0.4
  video_player: ^2.8.1
  image: ^4.1.3
  keep_screen_on: ^3.0.0
  vibration: ^1.8.3
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  bloc_test: ^9.1.5
  http_mock_adapter: ^0.6.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/hatofit.png"
  min_sdk_android: 28

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/logo/
    - assets/images/polar/
    - assets/images/avatar/
    - assets/images/icons/
    - assets/animations/
    - assets/videos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
