name: hatofit
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  firebase_performance: ^0.9.2+6
  firebase_analytics: ^10.5.0
  firebase_crashlytics: ^3.3.6
  firebase_remote_config: ^4.2.6
  firebase_core: ^2.16.0

  # Icons
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.4.0

  # BLE
  polar:
    path: packages/polar
  flutter_blue_plus:
    path: packages/flutter_blue_plus

  # State Management
  get: ^4.6.5

  # Preferences
  shared_preferences: ^2.2.0

  # Generator
  json_annotation: ^4.8.1
  image: ^4.0.17

  # UI
  flutter_svg: ^2.0.7
  lottie: ^2.4.0
  syncfusion_flutter_charts: ^21.2.6
  youtube_player_flutter: ^8.1.2
  cached_network_image: ^3.2.3
  horizontal_picker: ^1.2.0
  circular_countdown_timer:
    git:
      url: https://github.com/ceranco/circular_countdown_timer
      ref: on_change_fix
  image_picker: ^1.0.1
  video_player: ^2.7.0

  # Utils
  intl: ^0.18.1
  path_provider: ^2.0.15
  permission_handler: ^10.4.1
  vibration: ^1.8.1
  keep_screen_on: ^2.1.0

  # Notifications
  flutter_local_notifications: ^15.1.0+1
  logger: ^2.0.1
  health: ^8.0.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/logo/
    - assets/images/polar/
    - assets/images/avatar/
    - assets/images/icons/
    - assets/animations/
    - assets/videos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

icons_launcher:
  image_path: assets/images/icons/hatofit.png
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:
  image: assets/images/logo/light1.png
  color: "#ffffff"
  color_dark: "#1e1e1e"
  image_dark: assets/images/logo/dark1.png
  android_12:
    image: assets/images/logo/light1.png
    color: "#ffffff"
    color_dark: "#1e1e1e"
    image_dark: assets/images/logo/dark1.png
  android: true
  ios: true
