name: hatofit
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  dartz: ^0.10.1
  dio: ^5.4.0
  firebase_analytics: ^10.8.0
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.0.1
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  keep_screen_on: ^3.0.0
  logger: ^2.0.2+1
  oktoast: ^3.4.0
  polar: ^7.0.0
  pretty_dio_logger: ^1.3.1
  vibration: ^1.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/hatofit.png"
  min_sdk_android: 28

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/logo/
    - assets/images/polar/
    - assets/images/avatar/
    - assets/images/icons/
    - assets/videos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
